export const words = ["Dad delivered the dog to the vet",
    "Daytime job was bad",
    "Ted traveled today 22 kilometers",
    "Tanya tried to tell the truth",
    "When winter comes we will depart",
    "Tell Lilly, Lucy will leave on Monday morning",
    "Living a lie lead them to therapy",
    "Thunder and lightning lit up the sky",
    "On Sunday and Saturday the sunshine was shining",
    "Silver snake slithered silently through silver glass",
    "Ruben resolved this rude problem",
    "Ruth rattled the cage with a rat",
    "Jenna and Jay enjoyed their journey",
    "Jumping is joyful through spring meadows",
    "Thumping and twirling thumbs was the next challenge",
    "Think this thought through until Thursday thoroughly",
    "The carrier of Cartier brought his career into Korea",
    "The thirty-three thieves thought through that they thrilled the throne throughout Thursday",
    "Seth at Sainsburys sells thick socks",
    "He threw three free throws",
    "I saw Susie sitting in a shoe shine shop",
    "Where she sits she shines, where she shines she sits",
    "Roberta ran rings around the Roman ruins",
    "Clean clams crammed in clean cans",
    "Six sick hick nick six sick bricks with picks and sticks",
    "I wish to wish the wish you wish to wish, but if you wish the wish the witch wishes, I won’t wish the wish you wish to wish", 
    "Santas short suit shrank",
    "I was born on a pirate ship",
    "Wane went to Wales to watch walruses",
    "Six slick swans swam swiftly southwards",
    "Gobbling gargoyles gobbled gobbling goblins",
    "A big black bug bit a big black dog on his big black nose",
    "Ann and Andy anniversary is in April",
    "Fresh French fried fry fritters",
    "She sells seashells by the seashore"]